"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/languages/my-react-localization-plugin.pot",
    "translation": "/languages/my-react-localization-plugin-%locale%.po",
      "languages_mapping": {
         "locale": {
            "de": "de_DE",
            "fr": "fr_FR"
         }
      }
  }
]