name: Trigger Auto Translation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      text_domain:
        description: "Text domain (Defaults to repository name if text domain is missing)"
        required: false
        default: ""

jobs:
  translate:
    uses: https://github.com/mr-vara/workflows/.github/workflows/auto-translate.yml@main
    with:
      text_domain: ${{ github.event.inputs.text_domain }}
    secrets:
      TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
