name: Trigger Auto Translation

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions: {}

jobs:
  translate:
    name: 'Trigger Auto-Translate Workflow'
    permissions:
      contents: write
      pull-requests: write
    uses: mr-vara/workflows/.github/workflows/auto-translate.yml@main
    with:
      text_domain: 'my-react-localization-plugin'
    secrets:
      TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}

