name: Enforce Reviewers on PR

on:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  enforce-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Check for reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const reviewers = [...(github.context.payload.pull_request.requested_reviewers || [])];
            if (reviewers.length === 0) {
              const prNumber = github.context.payload.pull_request.number;
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                draft: true
              });
              core.setFailed("PR moved to draft: Reviewers must be assigned before requesting review.");
            }
