name: Enforce Reviewers on PR

on:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  check-reviewers:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Check for assigned reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const pr = github.context.payload.pull_request;
            const reviewers = pr.requested_reviewers || [];
            const teamReviewers = pr.requested_teams || [];

            if (reviewers.length === 0 && teamReviewers.length === 0) {
              // Revert PR to draft mode
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                draft: true
              });

              core.setFailed("❌ PR has no reviewers. It has been converted to draft. Please assign at least one reviewer.");
            } else {
              console.log("✅ Reviewers assigned. PR is ready for review.");
            }
